name: Deploy to EC2 Windows IIS

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish project
      run: dotnet publish -c Release -o publish

    - name: Stop IIS & clean target folder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        password: ${{ secrets.PASSWORD }}
        script: |
          Stop-Service W3SVC
          Remove-Item -Recurse -Force "C:\inetpub\wwwroot\carspot\*" -ErrorAction SilentlyContinue

    - name: Copy files to EC2 (SCP)
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        password: ${{ secrets.PASSWORD }}
        source: "publish"
        target: "C:/inetpub/wwwroot/carspot"
        strip_components: 1
        debug: true

    - name: Start IIS again
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        password: ${{ secrets.PASSWORD }}
        script: Start-Service W3SVC
